stages:
- stage: Test
  displayName: Chromatic Testing
  # Job list
  jobs:
  - job: Chromatic_Deploy
    displayName: Install packages and publishes to Chromatic

    steps:

    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: 'Install Node.js'  
    - task: Npm@1
      inputs:
        command: 'install'
        workingDir: '$(build.sourcesdirectory)'

    - task: CmdLine@2
      displayName: Publish to Chromatic
      inputs:
        script: npx chromatic --project-token=${CHROMATIC_PROJECT_TOKEN}